accounts/urls.py
from django.urls import path
from .import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register_view"),
    path("login/", views.LoginView.as_view(), name="login_view"),
    path("admin-login/", views.AdminLoginView.as_view(), name="admin_login_view"),
    path("logout/", views.LogoutView.as_view(), name="logout_view"),
    path("resident-dashboard/", views.ResidentDashboardView.as_view(), name="resident_dashboard_view"),
    path("admin-dashboard/", views.AdminDashboardView.as_view(), name="admin_dashboard_view"),
]

home/urls.py
from django.urls import path
from .import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
]

residenttoken/urls.py
from django.urls import path
from .import views

app_name = "residenttoken"

urlpatterns = [
    path("generate-resident-token/", views.GenerateResidentToken.as_view(), name="generate_resident_token_view"),
    path("verify-resident-token/", views.VerifyResidentToken.as_view(), name="verify_resident_token_view"),
]

spurtech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("token/", include("residenttoken.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

residenttoken/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ResidentToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=6)
    expired = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from residenttoken.models import ResidentToken


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "accounts/register.html")
    
    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        password = request.POST.get("password")
        estate_name = request.POST.get("estate_name")
        state = request.POST.get("state")
        if User.objects.filter(email=email).exists():
            message = "The email is already registered"
            return redirect("accounts:register_view")
        else:
            new_user = User.objects.create_user(username=email, email=email, password=password)
            new_user.save()
            return redirect("accounts:login_view")
        

class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "accounts/login.html")
    
    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        password = request.POST.get("password")
        if User.objects.filter(email=email).exists():
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                messages = f"Welcome back {email}"
                return redirect("accounts:resident_dashboard_view")
            else:
                print("not finally")
                message = "Incorrect credentials "
                return redirect("accounts:login_view")
        else:
            message = "No account with that credentials"
            return redirect("accounts:login_view")


class AdminLoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "accounts/admin-login.html")
    
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")
        if User.objects.filter(username=username).exists():
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_superuser:
                login(request, user)
                messages = f"Welcome back {username}"
                return redirect("accounts:admin_dashboard_view")
            else:
                print("not finally")
                message = "Incorrect credentials "
                return redirect("accounts:admin_login_view")
        else:
            message = "No account with that credentials"
            return redirect("accounts:admin_login_view")


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        message = "You've logged out"
        return redirect("home:home_view")


class ResidentDashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            token = ResidentToken.objects.filter(user=request.user).order_by("-timestamp").first()
        except:
            token = None
        context = {
            "token":token
        }
        return render(request, "accounts/resident-dashboard.html", context)
    

class AdminDashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, "accounts/admin-dashboard.html")

home/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home/index.html")

residenttoken/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import ResidentToken
from .generate_token import gen_token
from django.http import JsonResponse

# Create your views here.

class GenerateResidentToken(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        token = None
        if ResidentToken.objects.filter(user=request.user).exists():
            ResidentToken.objects.filter(user=request.user).delete()
            token = ResidentToken.objects.create(user=request.user, token=gen_token())
        else:
            token = ResidentToken.objects.create(user=request.user, token=gen_token())
        data = {
            "token":token.token,
        }
        return JsonResponse(data)
    

class VerifyResidentToken(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        token = request.POST.get("token")
        if ResidentToken.objects.filter(token=token).exists():
            message = "success"
        else:
            message = "error"
        data = {
            "message": message
        }
        return JsonResponse(data)
    

accounts/templates/accounts/admin-dashboard.html
    {% block body %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

    <div class="jumbotron mt-5">
        <h1 class="display-4">Admin Dashboard</h1>
        <p class="lead">Welcome {{ request.user }}</p>
        <hr class="my-4">
        <div>
            <label for="">Enter Token:</label> <br>
            <input type="text" name="token" id="residentToken" maxlength="6" oninput="tokenFunction()">
        </div>
        <button id="confirmtokenBtn" class="btn btn-primary btn-lg" disabled>Confirm Token</button>
        <div>
            <p id="confirmationMessage"></p>
        </div>
    </div>



    <script>
        function tokenFunction() {
            let tokenValue = document.getElementById("residentToken").value;
            if (tokenValue.length == 6) {
                document.getElementById("confirmtokenBtn").removeAttribute("disabled")
            }
            else{
                document.getElementById("confirmtokenBtn").setAttribute("disabled","disabled")
            }
        }

        $(document).ready(function(){
            $('#confirmtokenBtn').on('click', function(e){
                $.ajax({
                    method:'POST',
                    url:"{% url 'residenttoken:verify_resident_token_view' %}",
                    data:{
                        csrfmiddlewaretoken:"{{ csrf_token }}",
                        token: document.getElementById("residentToken").value
                    }, 
                    success: function(data) {
                        
                        if (data.message == "success") {
                            document.getElementById("confirmationMessage").innerHTML = "Visitor confirm!"
                        } else {
                            document.getElementById("confirmationMessage").innerHTML = "Invalid code!"
                        }
                        
                    },
                });
                
            });
        });
    </script> 

    {% endblock body %}

accounts/templates/accounts/admin-login.html
{% extends "home/index.html" %}

{% block body %}

<form method="post">
    {% csrf_token %}
    <div class="mb-5 mt-5">
        <h3 class="text-center">Admin Login</h3>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="inputEmail4">Username</label>
        <input type="text" class="form-control" id="inputEmail4" placeholder="Username" name="username">
      </div>
      <div class="form-group col-md-12">
        <label for="inputPassword4">Password</label>
        <input type="password" class="form-control" id="inputPassword4" placeholder="Password" name="password">
      </div>
    </div>

    <button type="submit" class="btn btn-primary" style="width: 100%; text-align: center;">Sign in</button>

</form>

{% endblock body %}

accounts/templates/accounts/login.html
{% extends "home/index.html" %}

{% block body %}

<form method="post">
    {% csrf_token %}
    <div class="mb-5 mt-5">
        <h3 class="text-center">Login</h3>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="inputEmail4">Email</label>
        <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email">
      </div>
      <div class="form-group col-md-12">
        <label for="inputPassword4">Password</label>
        <input type="password" class="form-control" id="inputPassword4" placeholder="Password" name="password">
      </div>
    </div>

    <button type="submit" class="btn btn-primary" style="width: 100%; text-align: center;">Sign in</button>

</form>

{% endblock body %}

accounts/templates/accounts/register.html
{% extends "home/index.html" %}

{% block body %}

<form method="post">
    {% csrf_token %}
    <div class="mb-5 mt-5">
        <h3 class="text-center">Register</h3>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="inputEmail4">Email</label>
        <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email" required>
      </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
          <label for="inputState">State</label>
          <select id="inputState" class="form-control" disabled>
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
          <label for="inputState">Estate</label>
          <select id="inputState" class="form-control" disabled>
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="inputPassword4">Password</label>
            <input type="password" class="form-control" id="inputPassword4" placeholder="Password" name="password" required>
        </div>
    </div>

    <button type="submit" class="btn btn-primary" style="width: 100%; text-align: center;">Register</button>

</form>

{% endblock body %}

accounts/templates/accounts/resident-dashboard.html
    {% block body %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

    <div class="jumbotron mt-5">
        <h1 class="display-4">Resident Dashboard</h1>
        <p class="lead">Welcome {{ request.user }}</p>
        <hr class="my-4">
        {% if token %}
        <p><b id="token">{{ token.token }}</b> <button class="btn btn-transparent btn-sm" onclick="copyFunction()" id="copyBtn">Copy<i class="fas fas fa-copy uk-margin-small-left"></i></button></p>
        <p>Token Expiration: <span>Token Expires in 30min</span></p>
        {% else %}
        <p><b>No Token</b></p>
        {% endif %}
        <button id="tokenBtn" class="btn btn-primary btn-lg">Generate New Token</button>
    </div>



    <script>
        $(document).ready(function(){
            $('#tokenBtn').on('click', function(e){
                $.ajax({
                    method:'POST',
                    url:"{% url 'residenttoken:generate_resident_token_view' %}",
                    data:{
                        csrfmiddlewaretoken:"{{ csrf_token }}"
                    }, 
                    success: function(data) {
                        
                        document.getElementById("token").innerHTML = data.token;
                        
                    },
                });
                
            });
        });
    </script> 

    <script>
        function copyFunction(){
            const copyText = document.getElementById("token").innerHTML;
            console.log(copyText);

            // Copy the text inside the text field
            navigator.clipboard.writeText(copyText);

            // Change copy to copied
            document.getElementById("copyBtn").innerHTML = "Copied!";
            const myTimeout = setTimeout(changeTextBack, 2000);

            function changeTextBack() {
                document.getElementById("copyBtn").innerHTML = "Copy<i class='fas fas fa-copy uk-margin-small-left'></i>";
            }
        }
    </script>
    {% endblock body %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
</head>
<body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'home:home_view' %}">SPURTECH</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'home:home_view' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:resident_dashboard_view' %}">Resident Dashboard</a>
                </li>
              </ul>
              
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout_view' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register_view' %}">Register</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                      Login
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown"> 
                      <a class="dropdown-item" href="{% url 'accounts:admin_login_view' %}">As Admin</a>
                      <a class="dropdown-item" href="{% url 'accounts:login_view' %}">As Resident</a>
                    </div>
                </li>
                {% endif %}
              </ul>
            </div>
        </nav>

        {% block body %}
        <div class="jumbotron mt-5">
            <h1 class="display-4">Spur Technologies Official Homepage</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </div>
        {% endblock body %}
    </div>
    


    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>